apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: io9t1qiuq-go 
  janus-idp.io/tekton: io9t1qiuq-go
  backstage.io/kubernetes-id: io9t1qiuq-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: io9t1qiuq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml