apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: io9t1qiuq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: io9t1qiuq-go 
  name: io9t1qiuq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: io9t1qiuq-go 
